adds blog entry about mixed reality setup at BCX 24
eclipse-kuksa/kuksa-website pull request #78
Opened 2024-05-21 08:22 UTC by eriksven

2024-06-05 03:43 UTC, SebastianSchildt requested changes
The banner filesize is mich too large. It is more than 4MB and I noticed because with the connection in my current office that takes 15 sek to load....

Just saving it as PNG again without any changes in resolution (I guess it was saved with barely any PNG compression) gives 2.7 MiB, but I really think this should be a .jpg. 350kB example attached 

@eriksven  in case zou agree will you change/want me to change?

![2024-05-08-mixed-reality](https://github.com/eclipse-kuksa/kuksa-website/assets/3707124/5024766e-c86f-486b-ad61-50d9c55db2f3)

2024-06-07 08:49 UTC, eriksven commented
Sorry for the rookie mistake, I will change the picture.

2024-06-10 07:54 UTC, eriksven commented
> Sorry for the rookie mistake, I will change the picture.

The PR now contains a smaller version of the banner picture. @SebastianSchildt could you please have another look? Thanks

2024-06-10 12:10 UTC, SebastianSchildt approved these changes

2024-06-10 12:10 UTC, merged